# Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [ ]:
netflix = pd.read_csv('/content/drive/MyDrive/Copy of Copy of combined_data_1.txt.zip',
                      header = None,
                      names=['cust_id', 'rating', 'date'],
                      usecols=[0,1,2])

In [ ]:
netflix.head()

   cust_id  rating        date
0       1:     NaN         NaN
1  1488844     3.0  2005-09-06
2   822109     5.0  2005-05-13
3   885013     4.0  2005-10-19
4    30878     4.0  2005-12-26

In [ ]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   cust_id  object
 1   rating   float64
 2   date     object
dtypes: float64(1), object(2)
memory usage: 550.7+ MB

# Data Preprocessing

In [ ]:
netflix['date'] = pd.to_datetime( netflix['date'])

In [ ]:
netflix.head()

   cust_id  rating       date
0       1:     NaN        NaT
1  1488844     3.0 2005-09-06
2   822109     5.0 2005-05-13
3   885013     4.0 2005-10-19
4    30878     4.0 2005-12-26

In [ ]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24058263 entries, 0 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   cust_id  object
 1   rating   float64
 2   date     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 550.7+ MB

In [ ]:
netflix.isnull().sum()

cust_id       0
rating     4499
date       4499
dtype: int64

In [ ]:
movie_count = netflix.isnull().sum()

In [ ]:
movie_count = movie_count['rating']
movie_count

4499

In [ ]:
total_count = netflix['cust_id'].nunique()
total_count

475257

In [ ]:
customer_count = total_count - movie_count
customer_count

470758

In [ ]:
rating_count = netflix['cust_id'].count() - movie_count
rating_count

24053764

In [ ]:
stars = netflix['rating'].value_counts()
stars

rating
4.0    8085741
3.0    6904181
5.0    5506583
2.0    2439073
1.0    1118186
Name: count, dtype: int64

In [ ]:
movie_id = None
movie_np = []

for i in netflix['cust_id']:
  if':' in i:
    movie_id = int(i.replace(':', ''))
  movie_np.append(movie_id)

In [ ]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
netflix['movie_id'] = movie_np
netflix.head()

   cust_id  rating       date  movie_id
0       1:     NaN        NaT         1
1  1488844     3.0 2005-09-06         1
2   822109     5.0 2005-05-13         1
3   885013     4.0 2005-10-19         1
4    30878     4.0 2005-12-26         1

In [ ]:
netflix.dropna(inplace=True)

In [ ]:
netflix.head()

   cust_id  rating       date  movie_id
1  1488844     3.0 2005-09-06         1
2   822109     5.0 2005-05-13         1
3   885013     4.0 2005-10-19         1
4    30878     4.0 2005-12-26         1
5   823519     3.0 2004-05-03         1

In [ ]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 4 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   object
 1   rating    float64
 2   date      datetime64[ns]
 3   movie_id  int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 917.6+ MB

In [ ]:
netflix['cust_id'] = netflix['cust_id'].astype('int')

In [ ]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 4 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   int64
 1   rating    float64
 2   date      datetime64[ns]
 3   movie_id  int64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 917.6 MB

In [ ]:
title = pd.read_csv('/content/movies (1).csv', encoding='ISO-8859-1', usecols=[0,1,2])
title.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
title.rename(columns={'movieId':'movie_id'}, inplace=True)

In [ ]:
title.head()

,movie_id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

### Merging the dataset

In [ ]:
# Merging
netflix_merged = pd.merge(netflix, title, on='movie_id', how ='left')
netflix_merged.head()

,cust_id,rating,date,movie_id,title,genres
0,1488844,3.0,2005-09-06,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,822109,5.0,2005-05-13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,885013,4.0,2005-10-19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,30878,4.0,2005-12-26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,823519,3.0,2004-05-03,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy

# 1. Finding the list of most popular and liked genre

In [ ]:
popular_genre = (netflix_merged.groupby('genres')['rating']
                 .count())

In [ ]:
popular_genre.sort_values(ascending=False)

genres
Drama                                                4365603
Comedy                                               2485519
Horror                                               1161658
Comedy|Drama                                         1083616
Drama|Romance                                        1018947
                                                      ...
Animation|Children|Comedy|Fantasy|Musical|Romance         95
Adventure|Animation|Children|Drama|Sci-Fi                 94
Documentary|Musical|IMAX                                  64
Adventure|Fantasy|Romance|Sci-Fi|Thriller                 62
Adventure|Animation                                       60
Name: rating, Length: 479, dtype: int64

In [ ]:
liked_genre = (netflix_merged.groupby('genres')['rating']
               .mean()
               .sort_values(ascending = False)
               .reset_index()
               .rename(columns={'rating': 'avg_rating'})
)

liked_genre.head(10)

                                              genres  avg_rating
0                      Action|Crime|Mystery|Thriller    4.470761
1                                 Comedy|Musical|War    4.348704
2                          Action|Adventure|Children    4.344422
3  Adventure|Animation|Children|Comedy|Fantasy|Ro...    4.325245
4                               Action|Adventure|War    4.286960
5                      Drama|Fantasy|Horror|Thriller    4.267554
6                         Comedy|Documentary|Romance    4.254009
7          Action|Adventure|Mystery|Romance|Thriller    4.191339
8                                    Fantasy|Romance    4.171470
9                                Crime|Drama|Musical    4.170963

# 2. Finding what genre movies have received the best and worst ratings based on User Rating

In [ ]:
best_genre = liked_genre.loc[liked_genre['avg_rating'].idxmax()]
worst_genre = liked_genre.loc[liked_genre['avg_rating'].idxmin()]

print(f"Best Genre: {best_genre['genres']}")
print(f"Worst Genre: {worst_genre['genres']}")

Best Genre: Action|Crime|Mystery|Thriller
Worst Genre: Adventure|Comedy|Romance|War

# 3. Creating a model that finds the best suited Movie for one user in every genre

In [ ]:
#pip install numpy==1.26.4

In [ ]:
! pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)

In [ ]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import cross_validate

In [ ]:
reader= Reader()

In [ ]:
data = Dataset.load_from_df(netflix_merged[['cust_id', 'movie_id', 'rating']][:10000],reader)

In [ ]:
model = SVD()

In [ ]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.24009038, 1.22280806, 1.2233975 ]),
 'fit_time': (0.25187087059020996, 0.3935420513153076, 0.2749953269958496),
 'test_time': (0.06786298751831055, 0.046422481536865234, 0.02026820182800293)}

In [ ]:
trainset = data.build_full_trainset()
model.fit(trainset)

In [ ]:
user_rating = netflix_merged[netflix_merged['cust_id'] == 1331154]
user_rating

,cust_id,rating,date,movie_id,title,genres
694,1331154,4.0,2004-07-03,3,Grumpier Old Men (1995),Comedy|Romance
5170,1331154,4.0,2005-07-03,8,Tom and Huck (1995),Adventure|Children
31442,1331154,3.0,2001-03-23,18,Four Rooms (1995),Comedy
92810,1331154,4.0,2004-05-11,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama
224717,1331154,3.0,2000-07-07,44,Mortal Kombat (1995),Action|Adventure|Fantasy
...,...,...,...,...,...,...
23435195,1331154,4.0,2003-10-28,4389,Lost and Delirious (2001),Drama
23542087,1331154,2.0,2000-05-05,4402,Dr. Goldfoot and the Bikini Machine (1965),Comedy
23644999,1331154,4.0,2003-11-04,4432,Sweet Smell of Success (1957),Drama|Film-Noir
23839969,1331154,3.0,2004-06-17,4472,Bad Dreams (1988),Horror|Thriller
23981073,1331154,4.0,2001-10-28,4488,Colors (1988),Action|Crime|Drama

In [ ]:
user_1331154 = netflix_merged.copy()
user_1331154

,cust_id,rating,date,movie_id,title,genres
0,1488844,3.0,2005-09-06,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,822109,5.0,2005-05-13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,885013,4.0,2005-10-19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,30878,4.0,2005-12-26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,823519,3.0,2004-05-03,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...,...
24053759,2591364,2.0,2005-02-16,4499,Dirty Rotten Scoundrels (1988),Comedy
24053760,1791000,2.0,2005-02-10,4499,Dirty Rotten Scoundrels (1988),Comedy
24053761,512536,5.0,2005-07-27,4499,Dirty Rotten Scoundrels (1988),Comedy
24053762,988963,3.0,2005-12-20,4499,Dirty Rotten Scoundrels (1988),Comedy
24053763,1704416,3.0,2004-06-02,4499,Dirty Rotten Scoundrels (1988),Comedy

In [ ]:
user_1331154['Estimated_Score'] = user_1331154['movie_id'].apply(lambda x: model.predict(1331154,x).est)

In [ ]:
user_1331154

,cust_id,rating,date,movie_id,title,genres,Estimated_Score
0,1488844,3.0,2005-09-06,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.138307
1,822109,5.0,2005-05-13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.138307
2,885013,4.0,2005-10-19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.138307
3,30878,4.0,2005-12-26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.138307
4,823519,3.0,2004-05-03,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,4.138307
...,...,...,...,...,...,...,...
24053759,2591364,2.0,2005-02-16,4499,Dirty Rotten Scoundrels (1988),Comedy,3.442499
24053760,1791000,2.0,2005-02-10,4499,Dirty Rotten Scoundrels (1988),Comedy,3.442499
24053761,512536,5.0,2005-07-27,4499,Dirty Rotten Scoundrels (1988),Comedy,3.442499
24053762,988963,3.0,2005-12-20,4499,Dirty Rotten Scoundrels (1988),Comedy,3.442499
24053763,1704416,3.0,2004-06-02,4499,Dirty Rotten Scoundrels (1988),Comedy,3.442499